[tool.poetry]
name = "ehubx"
version = "2.1.5"
description = "library with base functionality for energy hub modelling wiht   pyomo"
authors = ["Dennis Beermann <dennis.beermann@empa.ch>", "Fierz Leonie"]
classifiers=['Development Status :: Development',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: GNU Affero General Public License v3 (AGPLv3)',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.8'
]

packages = [
    { include = "ehubx", from="src" }
]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26"
pandas = "^2.2"
Pyomo = "^6.8"
matplotlib = "^3.9"
PyYAML = "^6.0"
types-PyYAML = "^6.0"
tsam = "^2.0"
gurobipy = "11.0"

[tool.poetry.dev-dependencies]
pytest = "^8.3"
pytest-cov = "^5.0"
pytest-html = "^4.1"
flake8 = "^7.0"
sphinx = "^7.4"
sphinx_rtd_theme = "^2.0"
MyPy = "^1.11"
licenseheaders = "^0.8.8"

[build-system]
requires = ["poetry>=1.6.1"]
build-backend = "poetry.masonry.api"

[tool.black]
  line-length = 180
  include = '\.pyi?$'
[tool.pytest.ini_options]
testpaths = ["tests"]
