[tool.poetry]
name = "ehubx"
version = "2.2.3"
description = "A platform for modeling and optimizing energy systems based on the energy hub concept"
authors = ["Dennis Beermann <dennis.beermann@empa.ch>", "Fierz Leonie", "TODO"]
classifiers=['Development Status :: Development',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.11'
]

packages = [
    { include = "ehubx", from="src" }
]

[tool.poetry.dependencies]
python = ">=3.11,<3.14"
numpy = "^2.3.1"
pandas = "^2.2"
Pyomo = "^6.8"
matplotlib = "^3.9"
tsam = "^2.0"
gurobipy = [
  { version = ">=11,<12", markers = "python_version < '3.13'" },
  { version = ">=12,<13", markers = "python_version >= '3.13'" }
]
pyyaml = "^6.0.2"
scipy = "^1.16.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3"
pytest-cov = "^5.0"
pytest-html = "^4.1"
sphinx = "^7.4"
sphinx_rtd_theme = "^2.0"
MyPy = "^1.11"
ruff = "^0.9.9"
pre-commit = "^4.1.0"
types-pyyaml = "^6.0.12.20241230"
snakeviz = "^2.2.2"

[build-system]
requires = ["poetry>=1.6.1"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length=88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["C901"]

[tool.ruff.lint.isort]
known-first-party = ["ehubx"]
lines-after-imports = 2

[tool.ruff.format]
docstring-code-format = true
quote-style = "double"

[tool.mypy]
ignore_missing_imports = true
